#spring:
#  datasource:
#    url: "jdbc:mysql://${DB_HOST_NAME:localhost}:${DB_PORT:3307}/${DB_NAME:student_db}?createDatabaseIfNotExist=false&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
#    username: ${DB_USERNAME:root}
#    password: ${DB_PASSWORD:abcd}
#  jpa:
#    generate-ddl: false
#    show-sql: true
#    open-in-view: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl